/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shmemchainInterface_shmemchainInterface */

#ifndef _Included_shmemchainInterface_shmemchainInterface
#define _Included_shmemchainInterface_shmemchainInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef shmemchainInterface_shmemchainInterface_TYPE_INVALID
#define shmemchainInterface_shmemchainInterface_TYPE_INVALID 0L
#undef shmemchainInterface_shmemchainInterface_TYPE_ACTIVE
#define shmemchainInterface_shmemchainInterface_TYPE_ACTIVE 1L
#undef shmemchainInterface_shmemchainInterface_TYPE_GHOST
#define shmemchainInterface_shmemchainInterface_TYPE_GHOST 2L
#undef shmemchainInterface_shmemchainInterface_MAX_NODES
#define shmemchainInterface_shmemchainInterface_MAX_NODES 128L
/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_register_node
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1register_1node
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_register_node_special
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1register_1node_1special
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_unregister_node
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1unregister_1node
  (JNIEnv *, jclass, jint);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_update_node
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1update_1node
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_write_data
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1write_1data
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_write_data_bytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1write_1data_1bytes
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_write_data_blocking
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1write_1data_1blocking
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_read_data
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1read_1data
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_update_node_name
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1update_1node_1name
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     shmemchainInterface_shmemchainInterface
 * Method:    shmemchain_get_info
 * Signature: (I[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1get_1info
  (JNIEnv *, jclass, jint, jobjectArray, jintArray);


/*
 * Class:     shmemchainInterface
 * Method:    shmemchain_set_rate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1set_1rate ( JNIEnv *env, jclass java_class, jlong node_id, jint rate );

/*
 * Class:     shmemchainInterface
 * Method:    shmemchain_get_rate
 * Signature: (I)I
 */
JNIEXPORT jlong JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1get_1rate ( JNIEnv *env, jclass java_class, jint node_id );

/*
 * Class:     shmemchainInterface
 * Method:    shmemchain_set_blocksize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1set_1blocksize ( JNIEnv *env, jclass java_class, jint node_id, jint blocksize );

/*
 * Class:     shmemchainInterface
 * Method:    shmemchain_get_blocksize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_shmemchainInterface_shmemchainInterface_shmemchain_1get_1blocksize ( JNIEnv *env, jclass java_class, jint node_id );


#ifdef __cplusplus
}
#endif
#endif
